"""add file storage fields

Revision ID: dbaf76240047
Revises: 5e6791f9ecfb
Create Date: 2026-08-04 17:38:47.761459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaf76240047'
down_revision: Union[str, Sequence[str], None] = '5e6791f9ecfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'documents', ['stored_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'stored_filename')
    # ### end Alembic commands ###
